version: '3.2'

services:
  # unsure about starting the cli as a container
  # just ssh in manually?
  # cli:
  #   build: cli/.
  #   network_mode: host
  #   hostname: localhost
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - onos-controller

  mininet:
    image: ghcr.io/ng-cdi/intent-tester:latest
    environment:
      - MN_FLAGS=
      - TOPO=/mnt/topo.py
    privileged: true
    network_mode: host
    hostname: localhost
    stdin_open: true
    tty: true
    volumes:
      - ./batfish/:/extra/
      - ./mininet/:/mnt/
    depends_on:
      - onos-controller

  onos-controller:
    image: ghcr.io/ng-cdi/demo-onos:latest
    hostname: localhost
    ports:
      - 8101:8101
      - 8181:8181
      - 6633:6633
      - 6653:6653
      - 6640:6640
      - 9876:9876

  onos-reroute-api:
    image: ghcr.io/mavi0/onos-reroute-api:latest
    network_mode: host
    hostname: localhost
    tty: true
    volumes:
      - ./reroute-api/json:/reroute/json
    environment:
      - TERM=xterm-256color
