#!/usr/bin/env python3
import sys
sys.path.append('lib')
from charms.reactive import main, set_state
from charmhelpers.core.hookenv import action_fail, action_name


set_state('actions.{}'.format(action_name()))
try:
    main()
except Exception as e:
    action_fail(repr(e))
